name: lint-check

on:
  push:
  pull_request:
    branches:
      - main
      - develop

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js and Yarn
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Corepack
      run: npm install -g corepack

    - name: Active Corepack
      run: corepack enable

    - run: yarn set version stable

    - name: Install Dependencies
      run: yarn install

    - name: Run ESLint
      run: yarn lint

    - name: Reviewdog
      uses: reviewdog/action-eslint@v1
      with:
        reporter: github-check
        eslint_flags: "src/"

    # Slacké€šçŸ¥
    - name: Slack Notification on Success
      uses: slackapi/slack-github-action@v1.24.0
      if: ${{ success() }}
      with:
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    - name: Send GitHub Action trigger data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text": "ãƒ‡ãƒ—ãƒ­ã‚¤å¤±æ•—ã—ã¾ã—ãŸ: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "ãƒ‡ãƒ—ãƒ­ã‚¤å¤±æ•—ã—ã¾ã—ãŸ: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    - name: Send GitHub Action trigger data to Slack workflow
      id: slack2
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text": "ãƒ‡ãƒ—ãƒ­ã‚¤å¤±æ•—ã—ã¾ã—ãŸ\n result:${{ job.status }}\n lint-check Action: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "ãƒ‡ãƒ—ãƒ­ã‚¤å¤±æ•—ã—ã¾ã—ãŸ\n result:${{ job.status }}\n lint-check Action: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    - name: Send GitHub Action trigger data to Slack workflow
      id: slack3
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text": "ãƒ‡ãƒ—ãƒ­ã‚¤å¤±æ•—ã—ã¾ã—ãŸğŸ˜¢\n result: ${{ job.status }}\n lint-check Action: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "ãƒ‡ãƒ—ãƒ­ã‚¤å¤±æ•—ã—ã¾ã—ãŸğŸ˜¢\n result: ${{ job.status }}\n lint-check Action: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    - name: Send GitHub Action trigger data to Slack workflow
      id: slack4
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "ãƒ‡ãƒ—ãƒ­ã‚¤å¤±æ•—ã—ã¾ã—ãŸğŸ˜¢\n result: ${{ job.status }}\n lint-check Action: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
